# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 576450363a4b169eee8e42e8d4d1547daeab21d56279e4f954b4f6611c74da6ffd3ef6037feee75f18f271e92ad2d70d69db4b6db6e1fb1951b87b44cf6f9e90

test:
  secret_key_base: 51c80905c79b7a85526f3f4483787451957b0ae30507de6366f35e6ffbc5a367332abd545aeb7fc6e54918cc99694d40d47fbaedcf18e97f31cd87659c914a75

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
